### ISSUE TITLE
Slider en blanco

### ISSUE THREAD

**Issue by markosc** [bitcero/inception#1]
Slider aparece en blanco luego de actualizar Common Utilities 2.3.1.6 y XOOPS 2.5.7.1.
![slider](https://cloud.githubusercontent.com/assets/16872280/12541960/e9ae6f54-c2ea-11e5-8aec-ed0969e87bf3.jpg)

**Comment by bitcero** [comment]
¿Actualizaste los archivos de inception?

**Comment by markosc** [comment]
tengo la Versión 2.0.5

**Comment by bitcero** [comment]
Verificando...

**Comment by markosc** [comment]
sucede con la ultima versión de xoops 2.8 y los archivos master de github

**Comment by bitcero** [comment]
Este es el mismo problema que #2. Cierro el hilo. Saludos.
